describe('Initial layout test', () => {
  it('Visits the initial project page and checks basic layout', () => {
    cy.visit('/')
    cy.contains('Color Tests Generator')
    cy.contains('Choose your background')
    cy.get('[data-cy=color-selector]').should('have.length', 6)
    cy.contains('Add your thougths about this app')
    cy.get('[data-test=error-feedback]').should('have.length', 2)
    cy.get('[data-test=author-input]').should('have.class', 'form-control').should('have.attr', 'placeholder', 'Author').type('Armando P. Tamayo').should('have.value', 'Armando P. Tamayo')
    cy.get('[data-test=content-input]').should('have.class', 'form-control').should('have.attr', 'placeholder', 'Content').type('I love this app').should('have.value', 'I love this app')
    cy.get('[data-test=message-submit]').should('have.text', ' Add ').should('have.class', 'bg-orange')
    cy.get('[data-cy=fib]').should('have.length', 9)
    cy.get('[data-test=message-list]').should('have.css', 'position', 'absolute').should('have.css', 'backdrop-filter', 'blur(10px)')
    cy.get('[data-test=message]').should('have.length', 1)
    cy.get('[data-test=author]').contains('Armando J. Peña Tamayo')
    cy.get('[data-test=content]').contains('I love this app\'s color effect')
    cy.get('[data-test=date]').should('have.length', 1)
    cy.get('[data-test=delete-button]').should('have.class', 'btn-danger').contains('X')
  })
})
